[features]
seeds = false
skip-lint = false
[programs.localnet]
vote_market = "CgpagJ94phFKHBKkk4pd4YdKgfNCp5SzsiNwcLe73dc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/fzzyyti/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.account]]
address = "7Jmy8EEofM24NRcy5BUmqHgYmXqo5P2N35RBQ6uuJdDe"
filename = "./test-accounts/epoch-gauge.json"

[[test.validator.account]]
address = "C8tANDkvD7K1PHzFDoaK4HmYzjixkw6HFY6dv1akQ85e"
filename = "./test-accounts/epoch-gauge-vote.json"

[[test.validator.account]]
address = "9AVupV7YSsqNESDq2UzVhKU2cWXiJvavuepub4cHuiKv"
filename = "./test-accounts/epoch-gauge-voter.json"

[[test.validator.account]]
address = "C8CMP5RkRQneDtYruTNWbRXihorfXpYh7JdEXjia1DJL"
filename = "./test-accounts/escrow.json"

[[test.validator.account]]
address = "5wTqGdHmmLXcoHN1TTLeijGtKAdikJ99td35yTMLNVTs"
filename = "./test-accounts/gauge-vote.json"

[[test.validator.account]]
address = "5mMpr6k2AzWVcAPjoJTgfQfbe9HCHTjTUPJm8TxragF"
filename = "./test-accounts/gauge-voter.json"

[[test.validator.account]]
address = "28ZDtf6d2wsYhBvabTxUHTRT6MDxqjmqR7RMCp348tyU"
filename = "./test-accounts/gaugemeister.json"

[[test.validator.account]]
address = "8erad8kmNrLJDJPe9UkmTHomrMV3EW48sjGeECyVjbYX"
filename = "./test-accounts/locker.json"

[[test.validator.account]]
address = "3xC4eW6xhW3Gpb4T5sCKFe73ay2K4aUUfxL57XFdguJx"
filename = "./test-accounts/gauge.json"

