[features]
seeds = false
skip-lint = false

[programs.localnet]
vote_market = "VotAjwzAEF9ZLNAYEB1ivXt51911EqYGVu9NeaEKRyy"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --file ./tests/vote-market-voting.ts --file ./tests/vote-market-rewards.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://mainnet.helius-rpc.com/?api-key=efa64d65-80ac-4f32-a701-fba4acc33236"

[[test.validator.account]]
address = "28ZDtf6d2wsYhBvabTxUHTRT6MDxqjmqR7RMCp348tyU"
filename = "./test-accounts/gaugemeister.json"

[[test.validator.account]]
address = "3xC4eW6xhW3Gpb4T5sCKFe73ay2K4aUUfxL57XFdguJx"
filename = "./test-accounts/gauge.json"

[[test.validator.account]]
address = "2AtXU77mwCTgEEnpAvz9uFUWBNmt7f4rCCGQVKwQBGpw"
filename = "./test-accounts/epoch-gauge.json"

[[test.validator.account]]
address = "6pNteYRSaiAFzFDm8QUhrrrtTVnFBTb1DuXqNS21xXD3"
filename = "./test-accounts/escrow.json"

[[test.validator.account]]
address = "DjwouQT131wP1z6YhuRzNZ4DCDvBVXwzF7youRpgzB2D"
filename = "./test-accounts/gauge-voter.json"

[[test.validator.account]]
address = "BwqqrXwRKwvSNdhuWGMGg39C71qJBNhnTPzeqXAKi5jC"
filename = "./test-accounts/gauge-vote.json"

[[test.validator.account]]
address = "Fn5P9KHHNSVWq3LDxSeKxTPt2huM3HfV8Za42PYSaApq"
filename = "./test-accounts/escrow-no-vote.json"

[[test.validator.account]]
address = "AnoiRjkQfifC98RxdNRrCSvhrbQaqQgp8CG9k6hcUR9Y"
filename = "./test-accounts/gauge-voter-no-vote.json"

[[test.validator.account]]
address = "GNtF2YjawJJVgxLvTEgfRFj2MX6PjnVTgs3a2JdUQkSg"
filename = "./test-accounts/gauge-vote-no-vote.json"

[[test.validator.account]]
address = "89vsS5gQbaAqJsCEoJAHw31RWDquG97FttnQ4qqqUA37"
filename = "./test-accounts/locker.json"

[[test.validator.account]]
address = "4JNBYKYHTLEmZMZ8VHJsbnbH7h72pNN2xRfbns4togQJ"
filename = "./test-accounts/epoch-gauge-voter.json"

[[test.validator.account]]
address = "8gF5s9K79yJyCFn5k7C3F7CdEEvrZDJCVxpfkDMxAryh"
filename = "./test-accounts/epoch-gauge-vote.json"

[[test.validator.account]]
address = "GaugesLJrnVjNNWLReiw3Q7xQhycSBRgeHGTMDUaX231"
filename = "./test-accounts/gauge-program.json"

[[test.validator.account]]
address = "4RV2XFNPa5egEiMLru8814ZqxhZT8eeqFrTxdqxyTaZm"
filename = "./test-accounts/gauge-program-data.json"

[[test.validator.account]]
address = "8KPY9nyQu8bJ53tsXo9CKmbvaDSKjcqGhF771kjomixp"
filename = "./test-accounts/saber-locker-program.json"

[[test.validator.account]]
address = "EUupCTLfEdtgLMuhRF6iL7V3wAjwF2tpvDuDckggeQxT"
filename = "./test-accounts/saber-locker-program-data.json"

[[test.validator.clone]]
address = "LocktDzaV1W2Bm9DeZeiyz4J9zs4fRqNiYqQyracRXw"
