[features]
seeds = false
skip-lint = false

[programs.localnet]
vote_market = "CgpagJ94phFKHBKkk4pd4YdKgfNCp5SzsiNwcLe73dc"

[provider]
cluster = "Localnet"
wallet = "/home/fzzyyti/.config/solana/burner.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --file ./tests/vote-market-voting.ts --file ./tests/vote-market-rewards.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.account]]
address = "28ZDtf6d2wsYhBvabTxUHTRT6MDxqjmqR7RMCp348tyU"
filename = "./test-accounts/gaugemeister.json"

[[test.validator.account]]
address = "3xC4eW6xhW3Gpb4T5sCKFe73ay2K4aUUfxL57XFdguJx"
filename = "./test-accounts/gauge.json"

[[test.validator.account]]
address = "2AtXU77mwCTgEEnpAvz9uFUWBNmt7f4rCCGQVKwQBGpw"
filename = "./test-accounts/epoch-gauge.json"

[[test.validator.account]]
address = "FXLMDGpLirbot2DY9JCmeKZtvu1TFaWSszE1Bd1kQAn"
filename = "./test-accounts/escrow.json"

[[test.validator.account]]
address = "2VshMQTveehVLKvE6mMtxazzz2geq9DKtMJLTqFf79YN"
filename = "./test-accounts/gauge-voter.json"

[[test.validator.account]]
address = "3KQwaioayMgkUkrKsDCkQUS7cKrKkqVFko5EhDqhjZjt"
filename = "./test-accounts/gauge-vote.json"

[[test.validator.account]]
address = "C8CMP5RkRQneDtYruTNWbRXihorfXpYh7JdEXjia1DJL"
filename = "./test-accounts/escrow-no-vote.json"

[[test.validator.account]]
address = "5mMpr6k2AzWVcAPjoJTgfQfbe9HCHTjTUPJm8TxragF"
filename = "./test-accounts/gauge-voter-no-vote.json"

[[test.validator.account]]
address = "E3NpYfVxUJbUH375vC6MpZE54NZrqc79hvE4U3pUgvou"
filename = "./test-accounts/gauge-vote-no-vote.json"

[[test.validator.account]]
address = "8erad8kmNrLJDJPe9UkmTHomrMV3EW48sjGeECyVjbYX"
filename = "./test-accounts/locker.json"

[[test.validator.account]]
address = "3FeuhCpKsU8ETqgoKUhTfmVb1LqHkhEehrFxQyABzRbi"
filename = "./test-accounts/epoch-gauge-voter.json"

[[test.validator.account]]
address = "FMy6Vo76j6dJW4Y4sj6zwrq2rt4RW31LX4w5pcV7MZjJ"
filename = "./test-accounts/epoch-gauge-vote.json"

[[test.validator.clone]]
address = "GaugesLJrnVjNNWLReiw3Q7xQhycSBRgeHGTMDUaX231"

[[test.validator.clone]]
address = "LocktDzaV1W2Bm9DeZeiyz4J9zs4fRqNiYqQyracRXw"
