[features]
seeds = false
skip-lint = false

[programs.localnet]
vote_market = "VotAjwzAEF9ZLNAYEB1ivXt51911EqYGVu9NeaEKRyy"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --file ./tests/vote-market-voting.ts --file ./tests/vote-market-rewards.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://mainnet.helius-rpc.com/?api-key=efa64d65-80ac-4f32-a701-fba4acc33236"

[[test.validator.account]]
address = "28ZDtf6d2wsYhBvabTxUHTRT6MDxqjmqR7RMCp348tyU"
filename = "./test-accounts/gaugemeister.json"

[[test.validator.account]]
address = "3xC4eW6xhW3Gpb4T5sCKFe73ay2K4aUUfxL57XFdguJx"
filename = "./test-accounts/gauge.json"

[[test.validator.account]]
address = "2AtXU77mwCTgEEnpAvz9uFUWBNmt7f4rCCGQVKwQBGpw"
filename = "./test-accounts/epoch-gauge.json"

[[test.validator.account]]
address = "4ZmVuidiRvrJ8rsLwdVdjmG23dmj8maeFss7BKe5TTqe"
filename = "./test-accounts/escrow.json"

[[test.validator.account]]
address = "t8R5LLSvZH4CZy73NbbiYTzVPRuUog6MdCXLsB2KDXT"
filename = "./test-accounts/gauge-voter.json"

[[test.validator.account]]
address = "8aEdJK2LZny4Wnc4ASRrS1qvwi68xg9cwUZTi2kd9Dxh"
filename = "./test-accounts/gauge-vote.json"

[[test.validator.account]]
address = "F4UGaiMmLm8tgdbjMsGWZ8FomaXswjMC28Gh3zC6VFeK"
filename = "./test-accounts/escrow-no-vote.json"

[[test.validator.account]]
address = "HUodujZskcihgLGTXqDyVHp4jroFGHY8GKXumLmTZrrQ"
filename = "./test-accounts/gauge-voter-no-vote.json"

[[test.validator.account]]
address = "DqSo4qCQ8c9NUrdUqqr3mASEnLHv7KHBJSKN98AsNAFF"
filename = "./test-accounts/gauge-vote-no-vote.json"

[[test.validator.account]]
address = "8erad8kmNrLJDJPe9UkmTHomrMV3EW48sjGeECyVjbYX"
filename = "./test-accounts/locker.json"

[[test.validator.account]]
address = "9u2x4VquPHyML8CtT5YuGhzVg1gykppqQhHbY18F3bLp"
filename = "./test-accounts/epoch-gauge-voter.json"

[[test.validator.account]]
address = "4ZDLyMBYfmYavG7Xw4onNei9JrucH9Bcx5A7diBisbFt"
filename = "./test-accounts/epoch-gauge-vote.json"

[[test.validator.clone]]
address = "GaugesLJrnVjNNWLReiw3Q7xQhycSBRgeHGTMDUaX231"

[[test.validator.clone]]
address = "LocktDzaV1W2Bm9DeZeiyz4J9zs4fRqNiYqQyracRXw"

[toolchain]
anchor_version = "0.29.0"
