[features]
seeds = false
skip-lint = false
[programs.localnet]
vote_market = "CgpagJ94phFKHBKkk4pd4YdKgfNCp5SzsiNwcLe73dc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/fzzyyti/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
